# Generated by Django 3.1.3 on 2020-11-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201127_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_de_consulta',
            field=models.CharField(choices=[('0', 'Consulta'), ('1', 'Reclamo'), ('2', 'Sugerencia'), ('3', 'Felicitaciones')], default='0', max_length=1),
        ),
    ]
